### ISSUE TITLE
Insert IDR Frame failed on AMD Card(WX Pro 4100)

### ISSUE THREAD

**Issue by Just-D** [21pages/hwcodec#4]
Hi,
I clone the project, and add an api named **insert_idr_frame()**, to generate an IDR Frame.
The impl is adding  **av_opt_set(c->priv_data, "forced-idr", "1", 0);**  before **avcodec_open2()** , then set the picture type by encoder->frame->pict_type = AV_PICTURE_TYPE_I  before **avcodec_send_frame**.
This worked at Nvidia card, but no use for AMD card, did you have any idea?

Thanks.

**Comment by 21pages** [comment]
Compile a debug ffmpeg lib and debug

**Comment by Just-D** [comment]
**Ok, thanks.**
