### ISSUE TITLE
why Intel GPU is just partially available?

### ISSUE THREAD

**Issue by liyimeng** [21pages/hwcodec#8]
I find the lib use VAAPI, and according to https://trac.ffmpeg.org/wiki/HWAccelIntro, Intel GPU have good support on VAAPI.  Considering a lot devices running intel CPU with integrated GPU, I am curious why Intel GPU is seconded.

**Comment by 21pages** [comment]
qsv support Intel, README updated

**Comment by liyimeng** [comment]
> qsv support Intel, README updated

do you mean another way around, ` qsv dose not support Intel`  since I see you remove intel from readme completely, which disappointing me so much ;)

**Comment by liyimeng** [comment]
Meanwhile I read this https://en.wikipedia.org/wiki/Intel_Quick_Sync_Video, it seem Intel cards should be well supported since the tech we used are from Intel. It will be surprised that it work for others but not for their own ones.
